# -*- coding: utf-8 -*-
"""big_project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gTbdLgHWjsRqB3JFTDou8bs5_PV3Tctc
"""

import numpy as np
import matplotlib.pyplot as plt
from keras.preprocessing.image import ImageDataGenerator, load_img, img_to_array, array_to_img
from keras.layers import Conv2D, Flatten, MaxPooling2D, Dense
from keras.models import Sequential
from skimage import filters, morphology, color, io, util
from skimage import io, color, filters, util 
import cv2
import glob, os, random

from google.colab import drive  
drive.mount('/content/drive')

base_path = '/content/drive/MyDrive/dataset/'

img_list = glob.glob(os.path.join(base_path, '*/*.jpg'))

print(len(img_list))

def loadgambar():
  return[cv2.imread(file) for file in glob.glob("/content/drive/MyDrive/dataset/anorganik/*.jpg")]
fileanorganik=loadgambar()
print(len(fileanorganik))

def loadgambar():
  return [cv2.imread(file) for file in glob.glob('/content/drive/MyDrive/dataset/b3/*.jpg')]
fileb3=loadgambar()
print(len(fileb3))

def loadgambar():
  return [cv2.imread(file) for file in glob.glob('/content/drive/MyDrive/dataset/organik/*.jpg')]
fileorganik=loadgambar()
print(len(fileorganik))

anorganik=[] 
for i in range(0,len(fileanorganik)):
  gray = color.rgb2gray(fileanorganik[i])
  fi=filters.rank.median(gray,selem=morphology.square(3))
  anorganik.append(fi)

organik=[] 
for i in range(0,len(fileorganik)):
  gray = color.rgb2gray(fileorganik[i])
  fi=filters.rank.median(gray,selem=morphology.square(3))
  organik.append(fi)

b3=[] 
for i in range(0,len(fileb3)):
  gray = color.rgb2gray(fileb3[i])
  fi=filters.rank.median(gray,selem=morphology.square(3))
  b3.append(fi)

for j in range(100):
  plt.figure(figsize=(16,8))
  plt.subplot(1,3,1);plt.imshow(anorganik[j],cmap='gray',vmin=0,vmax=255)
  plt.title("anorganik");plt.axis("off")
  plt.subplot(1,3,2);plt.imshow(organik[j],cmap='gray',vmin=0,vmax=255)
  plt.title("organik");plt.axis("off")
  plt.subplot(1,3,3);plt.imshow(b3[j],cmap='gray',vmin=0,vmax=255)
  plt.title("b3");plt.axis("off")
  plt.show()

for i, img_path in enumerate(random.sample(img_list, 3)):
  img = load_img(img_path)
  img = img_to_array(img, dtype=np.uint8)
  plt.subplot(1,3,i+1)
  plt.imshow(img.squeeze())
  plt.axis("off")

train_datagen = ImageDataGenerator(
    rescale=1./255,
    shear_range=0.1,
    zoom_range=0.1,
    width_shift_range=0.1,
    height_shift_range=0.1,
    horizontal_flip=True,
    vertical_flip=True,
    validation_split=0.1
)

test_datagen = ImageDataGenerator(
    rescale=1./255,
    validation_split=0.1
)

train_generator = train_datagen.flow_from_directory(
    base_path,
    target_size=(300, 300),
    batch_size=16,
    class_mode='categorical',
    subset='training',
    seed=0
)
validation_generator = test_datagen.flow_from_directory(
    base_path,
    target_size=(300, 300),
    batch_size=16,
    class_mode='categorical',
    subset='validation',
    seed=0
)

labels = (train_generator.class_indices)
labels = dict((v,k) for k,v in labels.items())

print(labels)

model = Sequential([
    Conv2D(filters=32, kernel_size=3, padding='same', activation='relu', input_shape=(300, 300, 3)),
    MaxPooling2D(pool_size=2),

    Conv2D(filters=64, kernel_size=3, padding='same', activation='relu'),
    MaxPooling2D(pool_size=2),
    
    Conv2D(filters=32, kernel_size=3, padding='same', activation='relu'),
    MaxPooling2D(pool_size=2),
    
    Conv2D(filters=64, kernel_size=3, padding='same', activation='relu'),
    MaxPooling2D(pool_size=2),

    Flatten(),

    Dense(64, activation='relu'),

    Dense(3, activation='softmax')
])
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['acc'])
#loss function bisa diganti binari crossentropy
#optimizer bisa ganti yalu, 
model.
model.summary()

"""# Take a Shot"""

model.fit(train_generator, epochs=20, validation_data=validation_generator)

"""# Another Shot"""

model.fit(train_generator, epochs=20, validation_data=validation_generator)

model.fit(train_generator, epochs=20, validation_data=validation_generator)

mnist = DataBlock(
    blocks=(ImageBlock, CategoryBlock), 
    get_items=get_image_files,
    splitter = GrandparentSplitter(train_name = "train", valid_name
    = "valid"),  
    get_y=parent_label,
    item_tfms=Resize(224))

dls = mnist.dataloaders(PATH)
mnist = mnist.new(
        item_tfms = RandomResizedCrop(224, min_scale = 0.5),
        batch_tfms = aug_transforms())

dls = mnist.dataloaders(PATH,bs = 32)
learn.fit_one_cycle(2, 0.1)

PATH = Path('/content/drive/MyDrive/dataset/')
#exported model predictions 
#get images to run 
folder ='/content/drive/MyDrive/dataset/' 
#get model name 
name = '/mnist_model.pkl'
#load model with file/path 
modelex = str(PATH) + name
#load exported model 
learn = load_learner(modelex)
#pass in images to create test batch 
dl = learn.dls.test_dl(images)
pred_tensor, ignored, preds = learn.get_preds(dl=dl, with_decoded=True)
result = np.argmax(pred_tensor, 1)

test_x, test_y = validation_generator.__getitem__(1)

preds = model.predict(test_x)

plt.figure(figsize=(16, 16))
for i in range(10):
    plt.subplot(4, 4, i+1)
    plt.title('pred:%s / truth:%s' % (labels[np.argmax(preds[i])], labels[np.argmax(test_y[i])]))
    plt.imshow(test_x[i])

from IPython.display import display, Javascript
from google.colab.output import eval_js
from base64 import b64decode

def take_photo(filename='photo.jpg', quality=0.8):
  js = Javascript('''
    async function takePhoto(quality) {
      const div = document.createElement('div');
      const capture = document.createElement('button');
      capture.textContent = 'Capture';
      div.appendChild(capture);

      const video = document.createElement('video');
      video.style.display = 'block';
      const stream = await navigator.mediaDevices.getUserMedia({video: true});

      document.body.appendChild(div);
      div.appendChild(video);
      video.srcObject = stream;
      await video.play();

      // Resize the output to fit the video element.
      google.colab.output.setIframeHeight(document.documentElement.scrollHeight, true);

      // Wait for Capture to be clicked.
      await new Promise((resolve) => capture.onclick = resolve);

      const canvas = document.createElement('canvas');
      canvas.width = video.videoWidth;
      canvas.height = video.videoHeight;
      canvas.getContext('2d').drawImage(video, 0, 0);
      stream.getVideoTracks()[0].stop();
      div.remove();
      return canvas.toDataURL('image/jpeg', quality);
    }
    ''')
  display(js)
  data = eval_js('takePhoto({})'.format(quality))
  binary = b64decode(data.split(',')[1])
  with open(filename, 'wb') as f:
    f.write(binary)
  return filename

from IPython.display import Image
try:
  filename = take_photo()
  print('Saved to {}'.format(filename))
  # Show the image which was just taken.
  display(Image(filename))
except Exception as err:
  # Errors will be thrown if the user does not have a webcam or if they do not
  # grant the page permission to access it.
  print(str(err))

"""## Showing CV2 Images

The ``cv2.imshow()`` and ``cv.imshow()`` functions from the [opencv-python](https://github.com/skvark/opencv-python) package are incompatible with Jupyter notebook; see https://github.com/jupyter/notebook/issues/3935.

As a replacement, you can use the following function:
"""

from google.colab.patches import cv2_imshow

"""For example, here we download and display a PNG image of the Colab logo:"""

import cv2
img = cv2.imread('photo.jpg', cv2.IMREAD_UNCHANGED)
cv2_imshow(img)
cv2_title()

